steps:

- id: Retag dev
  name: gcr.io/cloud-builders/docker
  waitFor:
  - '-'
  entrypoint: bash
  args:
  - -exc
  - |
    docker pull gcr.io/$PROJECT_ID/k8s/dev:sha_$COMMIT_SHA
    docker tag gcr.io/$PROJECT_ID/k8s/dev:sha_$COMMIT_SHA gcr.io/$PROJECT_ID/k8s/dev:sha_$TAG_NAME

images:
- gcr.io/$PROJECT_ID/k8s/dev:sha_$TAG_NAME
